# First Duplicate

In [1]:
# Modify to work with numpyarrays

'''A: Make an array filled with zeros of size a.length. When scanning
the array and your encounter the number n, check if the corresponding
element of the zero array is still zero. It if its zeo, change to non-zero, else
return n as you have encountered a duplicate.
Guaranteed constraints:
1 ≤ a.length ≤ 10^5,
1 ≤ a[i] ≤ a.length.'''

def firstDuplicate(a) :
    '''Return the element in array a that occurs in the array
    more than once and has minimal index for its second occurrence.
    If there are not duplicates, return -1.'''

    seen = [0] * len(a)
    for element in a :
        if seen[element-1] == 0 :
            seen[element-1] = 1
        else :
            return element              
    return -1

b = [1, 1, 2, 2, 1]
print(firstDuplicate(b))
b = [8, 4, 6, 2, 6, 4, 7, 9, 5, 8]
print(firstDuplicate(b))
b = [2, 4, 3, 5, 1]
print(firstDuplicate(b))

def firstDuplicate(a):
    mySet=set()
    for el in a:
        if el in mySet:
            return el
        mySet.add(el)
    return -1


1
6
-1


# First Not Repeating Character

In [74]:

def firstNotRepeatingCharacter(s) :
    """Given a string s consisting of small English letters,
    find and return the first instance of a non-repeating
    character in it. If there is no such character, return '_'.
    ie. For s = "abacabad", the output should be
    firstNotRepeatingCharacter(s) = 'c'.
    ie. For s = "abacabaabacaba", the output should be
    firstNotRepeatingCharacter(s) = '_'."""    

    count = [0] * 26 # Pre-allocate space in case all letters are unique.

    for letter in s :
        count[ord(letter) - 97] += 1 # Convert char to ASCII value. Account for zero indexing and update count.        
    
    # Compare list of letters on the left to get the first occurence, not the first letter in alphabetical order.
    for letter in s :
        # Get the index of letter in the alphabet
        if count[ord(letter) - 97] == 1 :
            return letter

    return '_' # If no repeting characters.
    
    
print(firstNotRepeatingCharacter("z"))
print(firstNotRepeatingCharacter("abacabad"))
print(firstNotRepeatingCharacter("abacabaabacaba"))
print(firstNotRepeatingCharacter("ngna"))

def firstNotRepeatingCharacter(s):
    for c in s:
        if s.index(c) == s.rindex(c):
            return c
    return '_'


z
c
_
g


## Rotate Image
<p> Solve this task in-place (with O(1) additional memory). You are given an n x n 2D matrix that represents an image. Rotate the image by 90 degrees (clockwise).
    
<p> 1 ≤ a.length ≤ 100 At least one column, at most 100.
<p> a[i].length = a.length This are square matrices only.
<p> 1 ≤ a[i][j] ≤ 10^4 Each entry is positive and less than or eauql to 10^4

In [116]:
import numpy as np


def rotateImage(a) : 
    ''' Rotate 90 degrees input array'''
    return np.transpose(np.array(a[::-1]))



a = [[1,2,3], 
 [4,5,6], 
 [7,8,9]]
print(a)
print(a[::-1])
print(rotateImage(a))
print(rotateImage([1]))
a=[[10,9,6,3,7], 
 [6,10,2,9,7], 
 [7,6,3,8,2], 
 [8,9,7,9,9], 
 [6,8,6,8,2]]
print(rotateImage(a))

def rotateImage(a):
    a.reverse()
    for i in range(len(a)):
        for j in range(i):
            a[i][j], a[j][i] = a[j][i], a[i][j]
    return a


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[7, 8, 9], [4, 5, 6], [1, 2, 3]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
[1]
[[ 6  8  7  6 10]
 [ 8  9  6 10  9]
 [ 6  7  3  2  6]
 [ 8  9  8  9  3]
 [ 2  9  2  7  7]]


# Sudoku2

In [100]:
# Make isrowunique method to make code more compact
def sudoku2(grid) :

    import numpy as np
    
    for irow in range(9) :
        
        seen = set() 
        row = grid[irow]        
    
        for number in row : # Check rows.
            if number not in seen and str(number) != '.' :
                seen.add(number)
            elif number in seen :
                return False
        
    AT = list(map(list, zip(*grid))) # Check columns.
    for irow in range(9) :
        
        seen =set()
        row = AT[irow]
        
        for number in row :
            if number not in seen and str(number) != '.' :
                seen.add(number)
            elif number in seen :
                return False

    for i in range(3) : # row block
        for j in range (3) : # column block
            
            seen = set()
            subgrid_vec = np.array(grid)[3*i:3*(i+1),3*j:3*(j+1)].flatten() # vectorize subgrid
            
            for number in subgrid_vec :
                if number not in seen and str(number) != '.' :
                    seen.add(number)
                elif number in seen :
                    return False

    return True           
            
 
A = [[".",".",".","1","4",".",".","2","."], 
 [".",".","6",".",".",".",".",".","."], 
 [".",".",".",".",".",".",".",".","."], 
 [".",".","1",".",".",".",".",".","."], 
 [".","6","7",".",".",".",".",".","9"], 
 [".",".",".",".",".",".","8","1","."], 
 [".","3",".",".",".",".",".",".","6"], 
 [".",".",".",".",".","7",".",".","."], 
 [".",".",".","5",".",".",".","7","."]]

#%%timeit print(sudoku2(A))       
%timeit sudoku2(A)


def check_unique(nums):
    s = set()
    for num in nums:
        if num == '.':
            continue 
            
        if num in s:
            return False
        s.add(num)
    return True
        

def sudoku3(grid):
    for line in grid:
        if not check_unique(line):
            return False
    
    for i in range(9):
        if not check_unique([line[i] for line in grid]):
            return False
        
    for i in range(0,9,3):
        for j in range(0, 9, 3):
            if not check_unique(grid[i][j:j+3] + grid[i+1][j:j+3] + grid[i+2][j:j+3]):
                return False
            
    return True

247 µs ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Cryptarythm

In [51]:
def isCryptSolution(crypt, solution) :
    
    # Build dictionary to map crypt to equation
    mapping = dict()

    for pair in solution :
        mapping[pair[0]] = pair[1]    

    # Map crypt to equation
    idx = 0
    equation = [[],[],[]]
    
    for word in crypt :
        str_number = ''
        for letter in word :
            str_number += mapping[letter]
        if len(str_number) > 1 and str_number[0] == '0' :
            return False
        equation[idx] = int(str_number)
        idx += 1    
        
    # Is equation valid
    return equation[0] + equation[1] == equation[2]    


crypt = ["SEND", 
 "MORE", 
 "MONEY"]

solution = [["O","0"], 
 ["M","1"], 
 ["Y","2"], 
 ["E","5"], 
 ["N","6"], 
 ["D","7"], 
 ["R","8"], 
 ["S","9"]]

print(isCryptSolution(crypt, solution))

crypt = ["TEN", 
 "TWO", 
 "ONE"]

solution = [["O","1"], 
 ["T","0"], 
 ["W","9"], 
 ["E","5"], 
 ["N","4"]]

print(isCryptSolution(crypt, solution))

True
False
